package com.crowdcash.model.enums;

public enum NotificationType {
    REGISTRATION_SUCCESS,
    EMAIL_VERIFIED,
    CAMPAIGN_APPROVED,
    CAMPAIGN_REJECTED,
    CAMPAIGN_EXPIRED,
    CAMPAIGN_GOAL_ACHIEVED,
    DONATION_SUCCESS,
    REWARD_ASSIGNED,
    NEW_COMMENT,
    NEW_QUESTION,
    CAMPAIGN_UPDATE_POSTED,
    ADMIN_MESSAGE,
    REPORT_RECEIVED
}
